"""add payment related tables

Revision ID: 01a62f643f0a
Revises: b70d0cf61d4a
Create Date: 2025-11-30 19:01:27.113088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a62f643f0a'
down_revision: Union[str, Sequence[str], None] = 'b70d0cf61d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bank_code', sa.String(length=4), nullable=False, comment='銀行コード（4桁）'),
    sa.Column('bank_name', sa.String(length=255), nullable=False, comment='銀行名'),
    sa.Column('bank_name_kana', sa.String(length=255), nullable=True, comment='銀行名カナ'),
    sa.Column('branch_code', sa.String(length=3), nullable=False, comment='支店コード（3桁）'),
    sa.Column('branch_name', sa.String(length=255), nullable=False, comment='支店名'),
    sa.Column('branch_name_kana', sa.String(length=255), nullable=True, comment='支店名カナ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banks'))
    )
    op.create_index(op.f('ix_banks_bank_code'), 'banks', ['bank_code'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='プロバイダーコード（例: credix, stripe）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='表示名（例: Credix, Stripe）'),
    sa.Column('credix_ip_code', sa.String(length=20), nullable=True, comment='Credix IPコード（clientip）'),
    sa.Column('credix_zkey', sa.String(length=100), nullable=True, comment='Credix認証キー（zkey）'),
    sa.Column('credix_webhook_url', sa.Text(), nullable=True, comment='Credix Webhook受信URL'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='プロバイダー固有設定（JSON）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=active, 2=inactive'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('code', name=op.f('uq_providers_code'))
    )
    op.create_table('bank_request_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='APIリクエストを実行したユーザー'),
    sa.Column('request_type', sa.SmallInteger(), nullable=False, comment='1=bank_search(銀行検索), 2=branch_search(支店検索), 3=account_verify(口座確認)'),
    sa.Column('bank_code', sa.String(length=4), nullable=True, comment='銀行コード（検索時）'),
    sa.Column('branch_code', sa.String(length=3), nullable=True, comment='支店コード（検索時）'),
    sa.Column('account_number', sa.String(length=20), nullable=True, comment='口座番号（確認時）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bank_request_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_request_histories'))
    )
    op.create_index(op.f('ix_bank_request_histories_user_id'), 'bank_request_histories', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='1=single, 2=plan'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=pending, 2=completed, 3=failed'),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False, comment='plan_id or price_id'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='credixから発行されたセッションID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_payment_transactions_provider_id_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions'))
    )
    op.create_table('user_banks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.SmallInteger(), nullable=False, comment='1=普通, 2=当座, 3=貯蓄'),
    sa.Column('account_number', sa.String(length=20), nullable=False, comment='口座番号（暗号化推奨）'),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False, comment='口座名義人'),
    sa.Column('account_holder_name_kana', sa.String(length=255), nullable=True, comment='口座名義人カナ'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='デフォルト振込先口座か'),
    sa.Column('verification_status', sa.SmallInteger(), nullable=False, comment='1=unverified, 2=verified, 3=rejected'),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='承認した管理者'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_user_banks_bank_id_banks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_banks_user_id_users')),
    sa.ForeignKeyConstraint(['verified_by'], ['admins.id'], name=op.f('fk_user_banks_verified_by_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_banks'))
    )
    op.create_index(op.f('ix_user_banks_user_id'), 'user_banks', ['user_id'], unique=False)
    op.create_table('user_providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('sendid', sa.String(length=25), nullable=True, comment='CredixカードID（リピーター決済用）'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='カード情報が有効か'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最終決済日時'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_user_providers_provider_id_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_providers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_providers'))
    )
    op.create_index(op.f('ix_user_providers_sendid'), 'user_providers', ['sendid'], unique=False)
    op.create_index(op.f('ix_user_providers_user_id'), 'user_providers', ['user_id'], unique=False)
    op.create_table('withdraws',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_bank_id', sa.UUID(), nullable=False),
    sa.Column('withdraw_amount', sa.BigInteger(), nullable=False, comment='出金申請金額（円）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=pending, 2=processing, 3=completed, 4=failed, 5=cancelled'),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='処理開始日時'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='処理完了日時'),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], name=op.f('fk_withdraws_approved_by_admins')),
    sa.ForeignKeyConstraint(['user_bank_id'], ['user_banks.id'], name=op.f('fk_withdraws_user_bank_id_user_banks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdraws_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdraws'))
    )
    op.create_index(op.f('ix_withdraws_status'), 'withdraws', ['status'], unique=False)
    op.create_index(op.f('ix_withdraws_user_id'), 'withdraws', ['user_id'], unique=False)
    # Drop foreign key constraint on payments.order_id before dropping orders table
    op.drop_constraint(op.f('fk_payments_order_id_orders'), 'payments', type_='foreignkey')
    # Drop tables with dependencies in correct order
    op.drop_index(op.f('idx_entitlements_user_scope'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_table('payment_events')
    op.drop_table('refunds')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.add_column('payments', sa.Column('transaction_id', sa.UUID(), nullable=False, comment='元となったCredixトランザクション'))
    op.add_column('payments', sa.Column('payment_type', sa.SmallInteger(), nullable=False, comment='1=subscription(plan_id), 2=one_time_purchase(price_id)'))
    op.add_column('payments', sa.Column('order_type', sa.SmallInteger(), nullable=False, comment='1=plan_id, 2=price_id'))
    op.add_column('payments', sa.Column('provider_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('buyer_user_id', sa.UUID(), nullable=False, comment='支払った人（購入者）'))
    op.add_column('payments', sa.Column('seller_user_id', sa.UUID(), nullable=False, comment='販売者（クリエイター）'))
    op.add_column('payments', sa.Column('payment_amount', sa.BigInteger(), nullable=False, comment='支払総額（buyer_user_idが実際に支払った金額 = item_price + purchase_fee）'))
    op.add_column('payments', sa.Column('payment_price', sa.BigInteger(), nullable=False, comment='支払い金額（price or plan.price）'))
    op.add_column('payments', sa.Column('failure_code', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('failure_message', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(), nullable=True, comment='実際の決済完了日時'))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               comment='plan_id（サブスク）またはprice_id（単品販売）',
               existing_nullable=False)
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.TEXT(),
               comment='Credix決済ID（session_id）',
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.SMALLINT(),
               comment='1=pending, 2=succeeded, 3=failed, 4=refunded, 5=partially_refunded',
               existing_nullable=False)
    op.create_index(op.f('ix_payments_buyer_user_id'), 'payments', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_seller_user_id'), 'payments', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_foreign_key(op.f('fk_payments_provider_id_providers'), 'payments', 'providers', ['provider_id'], ['id'])
    op.create_foreign_key(op.f('fk_payments_transaction_id_payment_transactions'), 'payments', 'payment_transactions', ['transaction_id'], ['id'])
    op.create_foreign_key(op.f('fk_payments_buyer_user_id_users'), 'payments', 'users', ['buyer_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_payments_seller_user_id_users'), 'payments', 'users', ['seller_user_id'], ['id'])
    op.drop_column('payments', 'amount')
    op.drop_column('payments', 'processed_at')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'currency')
    op.add_column('subscriptions', sa.Column('access_type', sa.SmallInteger(), nullable=False, comment='1=plan_subscription（プラン購読）, 2=one_time_purchase（単品購入）'))
    op.add_column('subscriptions', sa.Column('creator_id', sa.UUID(), nullable=False, comment='クリエイター（販売者）'))
    op.add_column('subscriptions', sa.Column('order_id', sa.String(length=255), nullable=False, comment='plan_id（サブスク）またはprice_id（単品販売）'))
    op.add_column('subscriptions', sa.Column('order_type', sa.SmallInteger(), nullable=False, comment='1=plan_id, 2=price_id'))
    op.add_column('subscriptions', sa.Column('access_start', sa.DateTime(), nullable=False, comment='視聴可能開始日（プラン: 課金開始日、単品: 購入日）'))
    op.add_column('subscriptions', sa.Column('access_end', sa.DateTime(), nullable=True, comment='視聴可能終了日（プラン: 課金期間終了日、単品: NULL=永久アクセス）'))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, comment='プラン購読: 期末でキャンセル予定（access_endまで視聴可能）'))
    op.add_column('subscriptions', sa.Column('next_billing_date', sa.DateTime(), nullable=True, comment='プラン購読: 次回課金予定日（バッチでチェック）'))
    op.add_column('subscriptions', sa.Column('failed_payment_count', sa.SmallInteger(), nullable=False, comment='プラン購読: 連続課金失敗回数'))
    op.add_column('subscriptions', sa.Column('last_payment_failed_at', sa.DateTime(), nullable=True, comment='プラン購読: 最終課金失敗日時'))
    op.add_column('subscriptions', sa.Column('provider_id', sa.UUID(), nullable=True, comment='決済プロバイダーID'))
    op.add_column('subscriptions', sa.Column('payment_id', sa.UUID(), nullable=True, comment='初回決済ID（または最新の決済ID）'))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment='購入者（この人に視聴権限を付与）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.SMALLINT(),
               comment='1=active（視聴可）, 2=canceled（期末まで視聴可）, 3=expired（期限切れ）, 4=refunded（返金済み）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'canceled_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='プラン購読: キャンセル申請日時',
               existing_nullable=True)
    op.create_index(op.f('ix_subscriptions_access_end'), 'subscriptions', ['access_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_access_start'), 'subscriptions', ['access_start'], unique=False)
    op.create_index(op.f('ix_subscriptions_access_type'), 'subscriptions', ['access_type'], unique=False)
    op.create_index(op.f('ix_subscriptions_creator_id'), 'subscriptions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_billing_date'), 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_subscriptions_plan_id_plans'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_payment_id_payments'), 'subscriptions', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(op.f('fk_subscriptions_creator_id_users'), 'subscriptions', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('fk_subscriptions_provider_id_providers'), 'subscriptions', 'providers', ['provider_id'], ['id'])
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('subscriptions', 'current_period_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_subscriptions_provider_id_providers'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscriptions_creator_id_users'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscriptions_payment_id_payments'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_plan_id_plans'), 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_creator_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_access_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_access_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_access_end'), table_name='subscriptions')
    op.alter_column('subscriptions', 'canceled_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='プラン購読: キャンセル申請日時',
               existing_nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='1=active（視聴可）, 2=canceled（期末まで視聴可）, 3=expired（期限切れ）, 4=refunded（返金済み）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='購入者（この人に視聴権限を付与）',
               existing_nullable=False)
    op.drop_column('subscriptions', 'payment_id')
    op.drop_column('subscriptions', 'provider_id')
    op.drop_column('subscriptions', 'last_payment_failed_at')
    op.drop_column('subscriptions', 'failed_payment_count')
    op.drop_column('subscriptions', 'next_billing_date')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'access_end')
    op.drop_column('subscriptions', 'access_start')
    op.drop_column('subscriptions', 'order_type')
    op.drop_column('subscriptions', 'order_id')
    op.drop_column('subscriptions', 'creator_id')
    op.drop_column('subscriptions', 'access_type')
    op.add_column('payments', sa.Column('currency', sa.CHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('provider', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_payments_seller_user_id_users'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_buyer_user_id_users'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_transaction_id_payment_transactions'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_provider_id_providers'), 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_seller_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_buyer_user_id'), table_name='payments')
    op.alter_column('payments', 'status',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='1=pending, 2=succeeded, 3=failed, 4=refunded, 5=partially_refunded',
               existing_nullable=False)
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Credix決済ID（session_id）',
               existing_nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               postgresql_using='order_id::uuid',
               comment=None,
               existing_comment='plan_id（サブスク）またはprice_id（単品販売）',
               existing_nullable=False)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'failure_message')
    op.drop_column('payments', 'failure_code')
    op.drop_column('payments', 'payment_price')
    op.drop_column('payments', 'payment_amount')
    op.drop_column('payments', 'seller_user_id')
    op.drop_column('payments', 'buyer_user_id')
    op.drop_column('payments', 'provider_id')
    op.drop_column('payments', 'order_type')
    op.drop_column('payments', 'payment_type')
    op.drop_column('payments', 'transaction_id')
    # Create tables in correct order (reverse of upgrade drop order)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_orders_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_orders'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creator_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name='fk_order_items_creator_user_id_users'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_items_order_id_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='fk_order_items_plan_id_plans'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_order_items_post_id_posts'),
    sa.PrimaryKeyConstraint('id', name='pk_order_items'),
    postgresql_ignore_search_path=False
    )
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('event_amount_cents', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    # Re-create foreign key from payments to orders
    op.create_foreign_key(op.f('fk_payments_order_id_orders'), 'payments', 'orders', ['order_id'], ['id'])
    op.create_table('entitlements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('creator_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('starts_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('granted_by_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('granted_by_subscription_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('granted_by_order_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_entitlements_creator_user_id_users')),
    sa.ForeignKeyConstraint(['granted_by_order_item_id'], ['order_items.id'], name=op.f('fk_entitlements_granted_by_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['granted_by_subscription_id'], ['subscriptions.id'], name=op.f('fk_entitlements_granted_by_subscription_id_subscriptions')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_entitlements_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entitlements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlements'))
    )
    op.create_index(op.f('idx_entitlements_user_scope'), 'entitlements', ['user_id', 'scope', 'creator_user_id', 'ends_at'], unique=False)
    op.drop_index(op.f('ix_withdraws_user_id'), table_name='withdraws')
    op.drop_index(op.f('ix_withdraws_status'), table_name='withdraws')
    op.drop_table('withdraws')
    op.drop_index(op.f('ix_user_providers_user_id'), table_name='user_providers')
    op.drop_index(op.f('ix_user_providers_sendid'), table_name='user_providers')
    op.drop_table('user_providers')
    op.drop_index(op.f('ix_user_banks_user_id'), table_name='user_banks')
    op.drop_table('user_banks')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_bank_request_histories_user_id'), table_name='bank_request_histories')
    op.drop_table('bank_request_histories')
    op.drop_table('providers')
    op.drop_index(op.f('ix_banks_bank_code'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
