"""add advertising_agencies tables

Revision ID: 0536cc98756c
Revises: 6f80a9b298d0
Create Date: 2025-12-12 11:58:10.308307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0536cc98756c'
down_revision: Union[str, Sequence[str], None] = '6f80a9b298d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_agencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertising_agencies')),
    sa.UniqueConstraint('code', name=op.f('uq_advertising_agencies_code'))
    )
    op.create_table('user_referrals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.Text(), nullable=False),
    sa.Column('registration_source', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['advertising_agencies.id'], name=op.f('fk_user_referrals_agency_id_advertising_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_referrals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_referrals'))
    )
    op.alter_column('payments', 'payment_type',
               existing_type=sa.SMALLINT(),
               comment='2=subscription(plan_id), 1=one_time_purchase(price_id)',
               existing_comment='1=subscription(plan_id), 2=one_time_purchase(price_id)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_type',
               existing_type=sa.SMALLINT(),
               comment='1=subscription(plan_id), 2=one_time_purchase(price_id)',
               existing_comment='2=subscription(plan_id), 1=one_time_purchase(price_id)',
               existing_nullable=False)
    op.drop_table('user_referrals')
    op.drop_table('advertising_agencies')
    # ### end Alembic commands ###
