"""add open_dm_flg plan table and add status clmoun conversion message table add message_assets table

Revision ID: 08a1bd44babe
Revises: cfd60e66a686
Create Date: 2025-12-19 14:17:10.920614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a1bd44babe'
down_revision: Union[str, Sequence[str], None] = 'cfd60e66a686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('asset_type', sa.SmallInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('reject_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], name=op.f('fk_message_assets_message_id_conversation_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_assets'))
    )
    op.add_column('conversation_messages', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('plans', sa.Column('open_dm_flg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'open_dm_flg')
    op.drop_column('conversation_messages', 'status')
    op.drop_table('message_assets')
    # ### end Alembic commands ###
