"""add_reject_comments_to_posts_and_media_assets

Revision ID: 0e7cabeca3c4
Revises: 6a27745e5990
Create Date: 2025-10-29 18:08:00.448662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7cabeca3c4'
down_revision: Union[str, Sequence[str], None] = '6a27745e5990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('reject_comments', sa.Text(), nullable=True))
    op.alter_column('plans', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='表示順序',
               existing_nullable=True)
    op.alter_column('plans', 'welcome_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='新規加入者へのメッセージ',
               existing_nullable=True)
    op.add_column('posts', sa.Column('reject_comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'reject_comments')
    op.alter_column('plans', 'welcome_message',
               existing_type=sa.TEXT(),
               comment='新規加入者へのメッセージ',
               existing_nullable=True)
    op.alter_column('plans', 'display_order',
               existing_type=sa.INTEGER(),
               comment='表示順序',
               existing_nullable=True)
    op.drop_column('media_assets', 'reject_comments')
    # ### end Alembic commands ###
