"""add platformfee in payments

Revision ID: 10411d0cadbe
Revises: 005bfb3ccdfc
Create Date: 2025-12-04 18:14:38.173472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10411d0cadbe'
down_revision: Union[str, Sequence[str], None] = '005bfb3ccdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('platform_fee', sa.SmallInteger(), nullable=False, comment='その時のプラットフォーム手数料'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'platform_fee')
    # ### end Alembic commands ###
