"""add sms_verifications table

Revision ID: 196125786048
Revises: a20a1a0ed45b
Create Date: 2025-10-22 18:43:54.796513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196125786048'
down_revision: Union[str, Sequence[str], None] = 'a20a1a0ed45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('purpose', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sms_verifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_verifications'))
    )
    op.create_index('idx_phone_e164_purpose', 'sms_verifications', ['phone_e164', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_phone_e164_purpose', table_name='sms_verifications')
    op.drop_table('sms_verifications')
    # ### end Alembic commands ###
