"""update notification for admin notification

Revision ID: 1c5169229dda
Revises: ddb4fa9f9b02
Create Date: 2026-01-16 11:31:48.818496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5169229dda'
down_revision: Union[str, Sequence[str], None] = 'ddb4fa9f9b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('target_role', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'target_role')
    # ### end Alembic commands ###
