"""add time_sale table for post and plan time sale infomation add sale price for check count

Revision ID: 27d9f6638ff0
Revises: fad2bf3eae05
Create Date: 2025-12-26 13:39:24.902031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d9f6638ff0'
down_revision: Union[str, Sequence[str], None] = 'fad2bf3eae05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_sale', sa.Column('sale_price', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_sale', 'sale_price')
    # ### end Alembic commands ###
