"""remove calomun post table

Revision ID: 42fd91054377
Revises: 6d461dbd3db9
Create Date: 2025-10-15 20:16:45.803700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42fd91054377'
down_revision: Union[str, Sequence[str], None] = '6d461dbd3db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'moderated_at')
    op.drop_column('posts', 'moderation_state')
    op.drop_column('posts', 'moderated_by')
    op.drop_column('posts', 'moderation_reason')
    op.drop_column('posts', 'moderation_flags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('moderation_flags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('moderation_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('moderated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('moderation_state', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('moderated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
