"""add cloums attempts sms_verfivations table

Revision ID: 5266e9b72579
Revises: 5398bb71ed31
Create Date: 2025-10-23 16:53:39.589796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5266e9b72579'
down_revision: Union[str, Sequence[str], None] = '5398bb71ed31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_verifications', sa.Column('attempts', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_verifications', 'attempts')
    # ### end Alembic commands ###
