"""add clomun is_phone_verified and phone_verified_at

Revision ID: 5398bb71ed31
Revises: 196125786048
Create Date: 2025-10-22 20:33:53.385920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398bb71ed31'
down_revision: Union[str, Sequence[str], None] = '196125786048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'is_phone_verified')
    # ### end Alembic commands ###
