"""update notifications models schema -> add updated at field

Revision ID: 56c5c8bd06e8
Revises: 8fcbba7af69f
Create Date: 2025-11-12 11:38:51.235515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c5c8bd06e8'
down_revision: Union[str, Sequence[str], None] = '8fcbba7af69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'updated_at')
    # ### end Alembic commands ###
