"""change  column session_id payment transaction

Revision ID: 674644aae68c
Revises: fa0a701f14b9
Create Date: 2025-12-05 17:18:26.747279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674644aae68c'
down_revision: Union[str, Sequence[str], None] = 'fa0a701f14b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='credixから発行されたセッションID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='credixから発行されたセッションID')
    # ### end Alembic commands ###
