"""add display_order and welcome_message to plans

Revision ID: 6a27745e5990
Revises: 829d79ea70e3
Create Date: 2025-10-28 15:17:56.557566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a27745e5990'
down_revision: Union[str, Sequence[str], None] = '829d79ea70e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('display_order', sa.Integer(), nullable=True, comment='表示順序'))
    op.add_column('plans', sa.Column('welcome_message', sa.Text(), nullable=True, comment='新規加入者へのメッセージ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'welcome_message')
    op.drop_column('plans', 'display_order')
    # ### end Alembic commands ###
