"""add is_main card flg user provider

Revision ID: 6f80a9b298d0
Revises: b4ace5abd5c9
Create Date: 2025-12-07 20:18:01.183429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f80a9b298d0'
down_revision: Union[str, Sequence[str], None] = 'b4ace5abd5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_providers', sa.Column('is_main_card', sa.Boolean(), nullable=False, comment='メインカードかどうか'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_providers', 'is_main_card')
    # ### end Alembic commands ###
