"""add banner table

Revision ID: 6fafd6a23b59
Revises: 0e7cabeca3c4
Create Date: 2025-11-06 18:21:30.808392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fafd6a23b59'
down_revision: Union[str, Sequence[str], None] = '0e7cabeca3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('cta_label', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('image_source', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_banners_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banners'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banners')
    # ### end Alembic commands ###
