"""add generete generation_media table

Revision ID: 71722609c439
Revises: fe1db16e47d5
Create Date: 2025-11-19 18:54:39.358084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71722609c439'
down_revision: Union[str, Sequence[str], None] = 'fe1db16e47d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_generation_media_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generation_media_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_media'))
    )
    op.alter_column('conversation_participants', 'participant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('uq_password_reset_tokens_token'), 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.drop_index(op.f('idx_posts_description_gin'), table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_bio_gin'), table_name='profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_username_gin'), table_name='profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_username_like'), table_name='profiles', postgresql_ops={'username': 'text_pattern_ops'})
    op.drop_index(op.f('idx_search_histories_query'), table_name='search_histories')
    op.drop_index(op.f('idx_search_histories_user_created'), table_name='search_histories')
    op.drop_index(op.f('idx_tags_name_gin'), table_name='tags', postgresql_using='gin')
    op.drop_index(op.f('idx_tags_name_like'), table_name='tags', postgresql_ops={'name': 'text_pattern_ops'})
    op.drop_index(op.f('idx_users_profile_name_gin'), table_name='users', postgresql_using='gin')
    op.drop_index(op.f('idx_users_profile_name_like'), table_name='users', postgresql_ops={'profile_name': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_profile_name_like'), 'users', ['profile_name'], unique=False, postgresql_ops={'profile_name': 'text_pattern_ops'})
    op.create_index(op.f('idx_users_profile_name_gin'), 'users', [sa.literal_column("to_tsvector('simple'::regconfig, profile_name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tags_name_like'), 'tags', ['name'], unique=False, postgresql_ops={'name': 'text_pattern_ops'})
    op.create_index(op.f('idx_tags_name_gin'), 'tags', [sa.literal_column("to_tsvector('simple'::regconfig, name)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_search_histories_user_created'), 'search_histories', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_search_histories_query'), 'search_histories', ['query'], unique=False)
    op.create_index(op.f('idx_profiles_username_like'), 'profiles', ['username'], unique=False, postgresql_ops={'username': 'text_pattern_ops'})
    op.create_index(op.f('idx_profiles_username_gin'), 'profiles', [sa.literal_column("to_tsvector('simple'::regconfig, username::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_bio_gin'), 'profiles', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(bio, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_posts_description_gin'), 'posts', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_unique_constraint(op.f('uq_password_reset_tokens_token'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.alter_column('conversation_participants', 'participant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('generation_media')
    # ### end Alembic commands ###
