"""add profile_image_submissions table

Revision ID: 829d79ea70e3
Revises: ba512785d039
Create Date: 2025-10-24 20:18:22.668604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829d79ea70e3'
down_revision: Union[str, Sequence[str], None] = 'ba512785d039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_image_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_type', sa.SmallInteger(), nullable=False, comment='1=avatar, 2=cover'),
    sa.Column('storage_key', sa.Text(), nullable=False, comment='S3ストレージキー'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=pending, 2=approved, 3=rejected'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True, comment='審査日時'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='却下理由'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], name=op.f('fk_profile_image_submissions_approved_by_admins')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_image_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_image_submissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_image_submissions')
    # ### end Alembic commands ###
