"""remove calomun and add cloumn medea_assets table

Revision ID: 896f66957d61
Revises: 42fd91054377
Create Date: 2025-10-16 19:04:13.570733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '896f66957d61'
down_revision: Union[str, Sequence[str], None] = '42fd91054377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('orientation', sa.SmallInteger(), nullable=True))
    op.drop_column('media_assets', 'width')
    op.drop_column('media_assets', 'height')
    op.drop_column('media_assets', 'hash_sha256')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('hash_sha256', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('media_assets', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_assets', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('media_assets', 'orientation')
    # ### end Alembic commands ###
