"""add cloums is_identity_verified  identity_verified_at users table

Revision ID: 8b1e089f4fa2
Revises: 5266e9b72579
Create Date: 2025-10-23 21:17:42.025046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1e089f4fa2'
down_revision: Union[str, Sequence[str], None] = '5266e9b72579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_identity_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('identity_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identity_verified_at')
    op.drop_column('users', 'is_identity_verified')
    # ### end Alembic commands ###
