"""add clomun authenticated_flag post table

Revision ID: 8d9015b741dc
Revises: 0e7cabeca3c4
Create Date: 2025-11-05 17:39:04.531165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9015b741dc'
down_revision: Union[str, Sequence[str], None] = '0e7cabeca3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('authenticated_flag', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'authenticated_flag')
    # ### end Alembic commands ###
