"""add time_sale table for post and plan time sale infomation

Revision ID: 99b5dfbb45d5
Revises: e8bc3136d51c
Create Date: 2025-12-23 12:22:18.878065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b5dfbb45d5'
down_revision: Union[str, Sequence[str], None] = 'e8bc3136d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
