"""remove clumun providers table

Revision ID: a238d2439d0b
Revises: e2536e20b207
Create Date: 2025-12-01 14:45:12.539292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a238d2439d0b'
down_revision: Union[str, Sequence[str], None] = 'e2536e20b207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'credix_zkey')
    op.drop_column('providers', 'credix_webhook_url')
    op.drop_column('providers', 'credix_ip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('credix_ip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Credix IPコード（clientip）'))
    op.add_column('providers', sa.Column('credix_webhook_url', sa.TEXT(), autoincrement=False, nullable=True, comment='Credix Webhook受信URL'))
    op.add_column('providers', sa.Column('credix_zkey', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Credix認証キー（zkey）'))
    # ### end Alembic commands ###
