"""add consumer_id  user_providers table

Revision ID: ab0331a16e84
Revises: 71b8c39a1f0a
Create Date: 2026-01-14 20:40:52.388458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0331a16e84'
down_revision: Union[str, Sequence[str], None] = '71b8c39a1f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_providers', sa.Column('provider_email', sa.String(length=255), nullable=True, comment='プロバイダーのメールアドレス'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_providers', 'provider_email')
    # ### end Alembic commands ###
