"""make_payments_transaction_and_provider_fields_nullable_for_free_subscriptions

Revision ID: b4ace5abd5c9
Revises: 674644aae68c
Create Date: 2025-12-07 16:50:10.410810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ace5abd5c9'
down_revision: Union[str, Sequence[str], None] = '674644aae68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_request_histories', 'bank_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Text(),
               existing_comment='銀行コード（検索時）',
               existing_nullable=True)
    op.alter_column('bank_request_histories', 'branch_code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Text(),
               existing_comment='支店コード（検索時）',
               existing_nullable=True)
    op.alter_column('bank_request_histories', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_comment='口座番号（確認時）',
               existing_nullable=True)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='元となったCredixトランザクション')
    op.alter_column('payments', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Credix決済ID（session_id）')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Credix決済ID（session_id）')
    op.alter_column('payments', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='元となったCredixトランザクション')
    op.alter_column('bank_request_histories', 'account_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_comment='口座番号（確認時）',
               existing_nullable=True)
    op.alter_column('bank_request_histories', 'branch_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=3),
               existing_comment='支店コード（検索時）',
               existing_nullable=True)
    op.alter_column('bank_request_histories', 'bank_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4),
               existing_comment='銀行コード（検索時）',
               existing_nullable=True)
    # ### end Alembic commands ###
