"""add post tracking

Revision ID: b4c6ee6bd26f
Revises: 370a76025981
Create Date: 2026-01-21 18:31:27.152921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c6ee6bd26f'
down_revision: Union[str, Sequence[str], None] = '370a76025981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views_tracking',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('watched_duration_sec', sa.Float(), nullable=True),
    sa.Column('video_duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_views_tracking'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_views_tracking')
    # ### end Alembic commands ###
