"""add cliumn platform_fee_percent creators table

Revision ID: b70d0cf61d4a
Revises: 71722609c439
Create Date: 2025-11-23 17:28:16.321543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70d0cf61d4a'
down_revision: Union[str, Sequence[str], None] = '71722609c439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('platform_fee_percent', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creators', 'platform_fee_percent')
    # ### end Alembic commands ###
