"""add cloums approved_by identity_verifications table

Revision ID: ba512785d039
Revises: 8b1e089f4fa2
Create Date: 2025-10-24 01:02:02.282583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba512785d039'
down_revision: Union[str, Sequence[str], None] = '8b1e089f4fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add approved_by column to identity_verifications table
    op.add_column('identity_verifications', sa.Column('approved_by', sa.UUID(), nullable=True))
    
    # Add foreign key constraint
    op.create_foreign_key('fk_identity_verifications_approved_by', 'identity_verifications', 'admins', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint('fk_identity_verifications_approved_by', 'identity_verifications', type_='foreignkey')
    
    # Drop approved_by column from identity_verifications table
    op.drop_column('identity_verifications', 'approved_by')
    # ### end Alembic commands ###
