"""add clomun is_referrer company_users table

Revision ID: be39fb48fcc5
Revises: 590329503a16
Create Date: 2025-11-12 20:15:22.988500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be39fb48fcc5'
down_revision: Union[str, Sequence[str], None] = '590329503a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_users', sa.Column('is_referrer', sa.Boolean(), nullable=True))

    # 既存のレコードにデフォルト値を設定
    op.execute("UPDATE company_users SET is_referrer = FALSE WHERE is_referrer IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_users', 'is_referrer')
    # ### end Alembic commands ###
