"""add open_dm_flg plan table

Revision ID: c7aa427695f8
Revises: cfd60e66a686
Create Date: 2025-12-16 17:09:43.811957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7aa427695f8'
down_revision: Union[str, Sequence[str], None] = 'cfd60e66a686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('open_dm_flg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'open_dm_flg')
    # ### end Alembic commands ###
