"""add cloumn advertising_agencies tables

Revision ID: cfd60e66a686
Revises: 0536cc98756c
Create Date: 2025-12-12 14:48:52.962079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd60e66a686'
down_revision: Union[str, Sequence[str], None] = '0536cc98756c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_access_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['advertising_agencies.id'], name=op.f('fk_agency_access_logs_agency_id_advertising_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency_access_logs'))
    )
    op.add_column('user_referrals', sa.Column('landing_page', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_referrals', 'landing_page')
    op.drop_table('agency_access_logs')
    # ### end Alembic commands ###
