"""add time_sale table for post and plan time sale infomation

Revision ID: d87f2aec632d
Revises: cfd60e66a686
Create Date: 2025-12-23 12:05:53.120525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87f2aec632d'
down_revision: Union[str, Sequence[str], None] = 'cfd60e66a686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
