"""update message assets including thumbnail

Revision ID: ddb4fa9f9b02
Revises: 71b8c39a1f0a
Create Date: 2026-01-15 11:02:35.756707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb4fa9f9b02'
down_revision: Union[str, Sequence[str], None] = '71b8c39a1f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_assets', sa.Column('thumbnail_storage_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_assets', 'thumbnail_storage_key')
    # ### end Alembic commands ###
