"""remove calomun and add cloumn medea_rendision_jobs table

Revision ID: dfc424e8f8be
Revises: 896f66957d61
Create Date: 2025-10-16 23:39:24.161804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfc424e8f8be'
down_revision: Union[str, Sequence[str], None] = '896f66957d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_rendition_jobs_rendition_id'), table_name='media_rendition_jobs')
    op.drop_constraint(op.f('fk_media_rendition_jobs_rendition_id_media_renditions'), 'media_rendition_jobs', type_='foreignkey')
    op.drop_column('media_rendition_jobs', 'rendition_id')
    op.drop_column('media_rendition_jobs', 'error_message')
    op.drop_column('media_rendition_jobs', 'master_manifest_key')
    op.drop_column('media_rendition_jobs', 'extra')
    op.drop_column('media_rendition_jobs', 'percent_complete')
    op.drop_column('media_renditions', 'height')
    op.drop_column('media_renditions', 'width')
    op.drop_column('media_renditions', 'duration_sec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_renditions', sa.Column('duration_sec', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('media_renditions', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_renditions', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_rendition_jobs', sa.Column('percent_complete', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('media_rendition_jobs', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('media_rendition_jobs', sa.Column('master_manifest_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('media_rendition_jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('media_rendition_jobs', sa.Column('rendition_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_media_rendition_jobs_rendition_id_media_renditions'), 'media_rendition_jobs', 'media_renditions', ['rendition_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_media_rendition_jobs_rendition_id'), 'media_rendition_jobs', ['rendition_id'], unique=False)
    # ### end Alembic commands ###
