"""update withdraws and banks_request_history

Revision ID: e2536e20b207
Revises: 01a62f643f0a
Create Date: 2025-12-01 10:45:50.702940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2536e20b207'
down_revision: Union[str, Sequence[str], None] = '01a62f643f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_request_histories', sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='APIレスポンスデータ'))
    op.add_column('withdraws', sa.Column('transfer_amount', sa.BigInteger(), nullable=False, comment='実際振込金額（円）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraws', 'transfer_amount')
    op.drop_column('bank_request_histories', 'response_data')
    # ### end Alembic commands ###
