"""add clomun offical_flg users table

Revision ID: eb0de42737ba
Revises: 708bee991849
Create Date: 2025-11-11 16:54:41.209416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0de42737ba'
down_revision: Union[str, Sequence[str], None] = '708bee991849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('offical_flg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'offical_flg')
    # ### end Alembic commands ###
