"""add clumun media_assets table

Revision ID: f26f8e9a3103
Revises: 6fafd6a23b59
Create Date: 2025-11-07 15:33:01.049904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26f8e9a3103'
down_revision: Union[str, Sequence[str], None] = '6fafd6a23b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('authenticated_flg', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'authenticated_flg')
    # ### end Alembic commands ###
