"""add user recommendations for feed

Revision ID: f3eb18bacaf6
Revises: 099f23ffaa1e
Create Date: 2026-01-26 16:58:50.918983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eb18bacaf6'
down_revision: Union[str, Sequence[str], None] = '099f23ffaa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_recommendations_user_type', 'user_recommendations', ['user_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_recommendations_user_type', 'user_recommendations', type_='unique')
    # ### end Alembic commands ###
