"""add payment_due_date column payment_transactions table

Revision ID: f69109366b21
Revises: 8d5d602656c2
Create Date: 2026-01-08 11:20:29.736684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69109366b21'
down_revision: Union[str, Sequence[str], None] = '8d5d602656c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('payment_due_date', sa.DateTime(), nullable=True, comment='決済期限日時'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'payment_due_date')
    # ### end Alembic commands ###
