"""add cliumn platform_fee_percent creators table ver 2

Revision ID: f9a2d7fee5a5
Revises: b70d0cf61d4a
Create Date: 2025-11-23 17:30:24.078948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a2d7fee5a5'
down_revision: Union[str, Sequence[str], None] = 'b70d0cf61d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creators', 'platform_fee_percent',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creators', 'platform_fee_percent',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
