"""add card info column user_provider tables

Revision ID: fa0a701f14b9
Revises: 2b5fb1502707
Create Date: 2025-12-04 20:25:27.981734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0a701f14b9'
down_revision: Union[str, Sequence[str], None] = '2b5fb1502707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_providers', sa.Column('cardbrand', sa.String(length=10), nullable=True, comment='カードブランド'))
    op.add_column('user_providers', sa.Column('cardnumber', sa.String(length=4), nullable=True, comment='カード番号'))
    op.add_column('user_providers', sa.Column('yuko', sa.String(length=4), nullable=True, comment='有効期限'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_providers', 'yuko')
    op.drop_column('user_providers', 'cardnumber')
    op.drop_column('user_providers', 'cardbrand')
    # ### end Alembic commands ###
