"""add time_sale table for post and plan time sale infomation

Revision ID: fad2bf3eae05
Revises: bb1c4adebf32
Create Date: 2025-12-24 15:35:19.101693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad2bf3eae05'
down_revision: Union[str, Sequence[str], None] = 'bb1c4adebf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_sale', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_sale', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
