"""add_search_histories_table_and_indexes

Revision ID: fe21859d00e6
Revises: 4c69f1134140
Create Date: 2025-11-14 13:10:39.380074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe21859d00e6'
down_revision: Union[str, Sequence[str], None] = '4c69f1134140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_histories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_histories'))
    )

    # 検索履歴テーブルのインデックス
    op.create_index('idx_search_histories_user_created', 'search_histories', ['user_id', sa.text('created_at DESC')])
    op.create_index('idx_search_histories_query', 'search_histories', ['query'])

    # 全文検索GINインデックス (PostgreSQL) - 'simple'設定を使用
    op.execute("CREATE INDEX idx_users_profile_name_gin ON users USING gin(to_tsvector('simple', profile_name))")
    op.execute("CREATE INDEX idx_profiles_username_gin ON profiles USING gin(to_tsvector('simple', username))")
    op.execute("CREATE INDEX idx_profiles_bio_gin ON profiles USING gin(to_tsvector('simple', COALESCE(bio, '')))")
    op.execute("CREATE INDEX idx_posts_description_gin ON posts USING gin(to_tsvector('simple', COALESCE(description, '')))")
    op.execute("CREATE INDEX idx_tags_name_gin ON tags USING gin(to_tsvector('simple', name))")

    # LIKE検索用インデックス (前方一致高速化)
    op.execute("CREATE INDEX idx_users_profile_name_like ON users(profile_name text_pattern_ops)")
    op.execute("CREATE INDEX idx_profiles_username_like ON profiles(username text_pattern_ops)")
    op.execute("CREATE INDEX idx_tags_name_like ON tags(name text_pattern_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # LIKE検索用インデックス削除
    op.execute("DROP INDEX IF EXISTS idx_tags_name_like")
    op.execute("DROP INDEX IF EXISTS idx_profiles_username_like")
    op.execute("DROP INDEX IF EXISTS idx_users_profile_name_like")

    # 全文検索GINインデックス削除
    op.execute("DROP INDEX IF EXISTS idx_tags_name_gin")
    op.execute("DROP INDEX IF EXISTS idx_posts_description_gin")
    op.execute("DROP INDEX IF EXISTS idx_profiles_bio_gin")
    op.execute("DROP INDEX IF EXISTS idx_profiles_username_gin")
    op.execute("DROP INDEX IF EXISTS idx_users_profile_name_gin")

    # 検索履歴インデックス削除
    op.drop_index('idx_search_histories_query', table_name='search_histories')
    op.drop_index('idx_search_histories_user_created', table_name='search_histories')

    op.drop_table('search_histories')
    # ### end Alembic commands ###
